name: CI

on: [push,pull_requests]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/steup--go@v5
        with:
          go-version: '1.25'
      - name: golangci-linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          export PATH=$PATH:$(go env GOPATH)/bin
      - run: make lint
      - run: make test

